using System;
using System.IO;
using System.Threading.Tasks;

namespace CodingSahayi;

/// <summary>
/// Generates <c>soup.yaml</c> configuration files for the Soup fine-tuning CLI.
/// The generated file targets LoRA fine-tuning with layer streaming enabled to
/// minimise VRAM usage on consumer hardware.
/// </summary>
public static class SoupConfigManager
{
    /// <summary>
    /// Generates a <c>soup.yaml</c> LoRA fine-tuning configuration and writes it
    /// inside a <c>.soup/</c> sub-directory of <paramref name="workspacePath"/>.
    /// </summary>
    /// <param name="workspacePath">Root of the training workspace (e.g. the project folder).</param>
    /// <param name="datasetPath">Absolute path to the JSONL dataset file produced by <see cref="DatasetExporter"/>.</param>
    /// <returns>Absolute path of the written <c>soup.yaml</c> file.</returns>
    public static async Task<string> GenerateSoupYaml(string workspacePath, string datasetPath)
    {
        var soupDir = Path.Combine(workspacePath, ".soup");
        if (!Directory.Exists(soupDir))
            Directory.CreateDirectory(soupDir);

        var yamlPath = Path.Combine(soupDir, "soup.yaml");

        // Retrieve the base model from settings; fall back to Qwen2.5-Coder-1.5B
        string baseModel = !string.IsNullOrWhiteSpace(SettingsManager.SoupBaseModel)
            ? SettingsManager.SoupBaseModel
            : (!string.IsNullOrWhiteSpace(SettingsManager.LocalModelName) && !SettingsManager.LocalModelName.Equals("local-model", StringComparison.OrdinalIgnoreCase)
                ? SettingsManager.LocalModelName
                : "Qwen/Qwen2.5-Coder-1.5B");

        // Output directory for the fine-tuned adapter / model
        string outputDir = Path.Combine(soupDir, "output").Replace('\\', '/');

        // Normalise dataset path to forward slashes for cross-platform YAML readability
        string datasetNorm = datasetPath.Replace('\\', '/');

        string yaml = $"""
# soup.yaml — Generated by Coding Sahayi on {DateTime.Now:yyyy-MM-dd HH:mm:ss}
# Fine-tuning configuration for Soup CLI (D:\Soup)
# Reference: https://github.com/MakazhanAlpamys/Soup

base: {baseModel}
task: sft

data:
  train: "{datasetNorm}"
  format: chatml
  val_split: 0.05
  max_length: 2048

training:
  epochs: 3
  lr: 0.0002
  batch_size: 1
  gradient_accumulation_steps: 8
  quantization: 4bit
  stream_layers: true
  lora:
    r: 16
    alpha: 32
    dropout: 0.05
    target_modules: auto

output: "{outputDir}"
""";

        await File.WriteAllTextAsync(yamlPath, yaml, System.Text.Encoding.UTF8);
        return yamlPath;
    }
}
