using System;
using System.IO;
using System.Threading.Tasks;

namespace CodingSahayi;

/// <summary>
/// Generates <c>soup.yaml</c> configuration files for the Soup fine-tuning CLI.
/// The generated file targets LoRA fine-tuning with layer streaming enabled to
/// minimise VRAM usage on consumer hardware.
/// </summary>
public static class SoupConfigManager
{
    /// <summary>
    /// Generates a <c>soup.yaml</c> LoRA fine-tuning configuration and writes it
    /// inside a <c>.soup/</c> sub-directory of <paramref name="workspacePath"/>.
    /// </summary>
    /// <param name="workspacePath">Root of the training workspace (e.g. the project folder).</param>
    /// <param name="datasetPath">Absolute path to the JSONL dataset file produced by <see cref="DatasetExporter"/>.</param>
    /// <returns>Absolute path of the written <c>soup.yaml</c> file.</returns>
    public static async Task<string> GenerateSoupYaml(string workspacePath, string datasetPath)
    {
        var soupDir = Path.Combine(workspacePath, ".soup");
        if (!Directory.Exists(soupDir))
            Directory.CreateDirectory(soupDir);

        var yamlPath = Path.Combine(soupDir, "soup.yaml");

        // Retrieve the local model name from settings; fall back to qwen2.5-coder
        string baseModel = SettingsManager.LocalModelName is { Length: > 0 } m
            ? m
            : "qwen2.5-coder";

        // Output adapter directory (written alongside the YAML)
        string outputDir = Path.Combine(soupDir, "lora-adapter").Replace('\\', '/');

        // Normalise dataset path to forward slashes for cross-platform YAML readability
        string datasetNorm = datasetPath.Replace('\\', '/');

        string yaml = $"""
# soup.yaml — Generated by Coding Sahayi on {DateTime.Now:yyyy-MM-dd HH:mm:ss}
# Fine-tuning configuration for the Soup CLI (LoRA / QLoRA).
# Docs: https://github.com/your-org/soup (adjust URL to the actual Soup repo)

# ── Model ─────────────────────────────────────────────────────────────────────
model_name_or_path: {baseModel}
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

# ── Dataset ───────────────────────────────────────────────────────────────────
datasets:
  - path: {datasetNorm}
    type: chat_template          # OpenAI chat-completion messages format

dataset_prepared_path: null
val_set_size: 0.05               # 5 % validation split

# ── LoRA adapter ──────────────────────────────────────────────────────────────
adapter: lora
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

# ── Quantisation (4-bit QLoRA) ────────────────────────────────────────────────
load_in_4bit: true
bnb_4bit_compute_dtype: bfloat16

# ── VRAM optimisation — layer streaming ───────────────────────────────────────
# Streams transformer layers on and off the GPU one at a time, dramatically
# reducing peak VRAM at the cost of slightly lower throughput.
layer_streaming: true

# ── Training hyperparameters ──────────────────────────────────────────────────
sequence_len: 2048
sample_packing: false

output_dir: {outputDir}

num_epochs: 3
micro_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 0.0002
lr_scheduler: cosine
warmup_steps: 20
optimizer: adamw_bnb_8bit
weight_decay: 0.0

# ── Logging & checkpoints ─────────────────────────────────────────────────────
logging_steps: 10
save_strategy: epoch
eval_steps: 50
report_to: none                  # set to "wandb" if you want W&B tracking

# ── Mixed precision ───────────────────────────────────────────────────────────
bf16: auto
fp16: false
tf32: false
""";

        await File.WriteAllTextAsync(yamlPath, yaml, System.Text.Encoding.UTF8);
        return yamlPath;
    }
}
